export const POSTS_REQUESTED = "POSTS_REQUESTED";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const CREATE_POSTS_REQUESTED = "CREATE_POSTS_REQUESTED";
export const CREATE_POSTS_SUCCESS = "CREATE_POSTS_SUCCESS";

export const DELETE_POSTS_REQUESTED = "DELETE_POSTS_REQUESTED";
export const DELETE_POSTS_SUCCESS = "DELETE_POSTS_SUCCESS";

export const UPDATE_POSTS_REQUESTED = "UPDATE_POSTS_REQUESTED";
export const UPDATE_POSTS_SUCCESS = "UPDATE_POSTS_SUCCESS";
